export const DROP_DOWN_CONTENT = {
    ACTION_UPDATE_STATE_ON: 'ACTION_UPDATE_STATE_ON',
    ACTION_UPDATE_STATE_OFF: 'ACTION_UPDATE_STATE_OFF'
  };
  
  export const MODAL = {
    ACTION_UPDATE_CONTENT: 'ACTION_UPDATE_CONTENT'
  };